# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hyperbudget-encryption

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2
  stage: ${env:TRAVIS_BRANCH, 'dev'}
  apiKeys:
    - ${self:provider.stage}-encryptionAPIKey

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  encryptData:
    handler: handler.encrypt
    events:
      - http:
          path: encrypt
          method: post
          private: true
  decryptData:
    handler: handler.decrypt
    events:
      - http:
          path: decrypt
          method: post
          private: true
